import MainFooter from "@/components/MainFooter";
import MainNav from "@/components/MainNav";
import Head from "next/head";
import Image from "next/image";

const Contact = () => {
  return (
    <>
      <Head>
        <title>About - Apex Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainNav />
        <div className="head-top-container">
          <div className="row">
            <div className="col-6"></div>
            <div className="col-6">
              <div className="head-img">
                <Image
                  src="/image/contact.jpg"
                  alt="contact-us"
                  height={480}
                  width={1440}
                />
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row top-head-position">
              <div className="col-6">
                <div className="top-head-position-inside">
                  <h1>Contact Apex Advisor Group Inc</h1>
                  <h4>
                    Accounting & Tax Preparation Firm In Tampa, Florida Notary |
                    Credit Repair & Counseling | Insurance
                  </h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container">
          <div className="row">
            <div className="col-6">
              <div className="contact-address">
                <h3>Address:</h3>
                <p>1211 TECH BLVD, SUITE 120, TAMPA, FL 33619</p>
                <h3>Phone:</h3>
                <a href="tel:(813) 678-2400">(813) 678-2400</a>
                <h3>Email:</h3>
                <a href="mailto: info@apexadvisor.pro">info@apexadvisor.pro</a>
                <h3>By Appointments:</h3>
                <p>MON - FRI - 09:00 AM - 05:00 PM</p>
                <p>AFTER HOURS AND WEEKENDS - AVAILABLE BY EMAIL</p>
              </div>
            </div>
            <div className="col-6">
              <div className="contact-form">
                <div className="contact-form-name-container">
                  <div className="contact-form-name">
                    <p>First Name *</p>
                    <input type="text" placeholder="Enter your first name." />
                  </div>
                  <div className="contact-form-name">
                    <p>Last Name *</p>
                    <input type="text" placeholder="Enter your last name." />
                  </div>
                </div>
                <p>Email *</p>
                <input type="text" placeholder="Enter your email." />
                <p>Phone *</p>
                <input type="text" placeholder="Enter your phone number." />
                <p>Your Organization (if any)</p>
                <input type="text" placeholder="Enter organization name." />
                <p>Message *</p>
                <textarea type="text" placeholder="Enter message." rows={7} />
                <button type="submit">Send</button>
              </div>
            </div>
          </div>
        </div>
        <iframe
          width="100%"
          height="300"
          className="contact-map"
          frameborder="0"
          marginheight="0"
          marginwidth="0"
          src="https://maps.google.com/maps?width=100%25&amp;height=300&amp;hl=en&amp;q=1211%20Tech%20Blvd%20Suite%20105+(Apex%20Advisor)&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
        />
        <MainFooter />
      </main>
    </>
  );
};

export default Contact;
