import MainFooter from "@/components/MainFooter";
import MainNav from "@/components/MainNav";
import Head from "next/head";
import Image from "next/image";

const ServicesArea = () => {
  return (
    <>
      <Head>
        <title>Service Area - Apex Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainNav />
        <div
          className="head-top-container"
          data-aos="fade-up"
          data-aos-delay="50"
          data-aos-duration="1000"
          data-aos-easing="ease"
        >
          <div className="row">
            <div className="col-6"></div>
            <div className="col-6">
              <div className="head-img">
                <Image
                  src="/image/services-area.jpg"
                  alt="accountant-services"
                  height={657}
                  width={1000}
                />
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row top-head-position">
              <div className="col-6">
                <div className="top-head-position-inside">
                  <h1>About Apex Advisor Group Inc</h1>
                  <h4>Service Area</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="conteiner">
          <div className="row">
            <div className="col-9"></div>
            <div className="col-3"></div>
          </div>
        </div>
        <MainFooter />
      </main>
    </>
  );
};

export default ServicesArea;
